# Generated by Django 6.0.1 on 2026-01-23 07:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognitionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='recognition/images/', verbose_name='原始图像')),
                ('preprocessed_image', models.ImageField(upload_to='recognition/preprocessed/', verbose_name='预处理后图像')),
                ('result', models.CharField(max_length=10, verbose_name='识别结果')),
                ('confidence', models.FloatField(verbose_name='置信度')),
                ('candidates', models.JSONField(verbose_name='候选字列表')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '识别记录',
                'verbose_name_plural': '识别记录',
                'ordering': ['-created_at'],
            },
        ),
    ]
